### ISSUE TITLE
find a name

### ISSUE THREAD

**Issue by nusenu** [tempname1024/allium#4]
If avoid getting email from the torproject about the name "tor-metrics" eventually
I'd recommend coming up with a new name you like.

**Comment by nusenu** [comment]
How about "ExploraTor" ?

**Comment by tempname1024** [comment]
> How about "ExploraTor" ?

I'm partial to onion-related words -- how about _allium_?

> al•li•um ăl′ē-əm
> Any of numerous, usually bulbous plants of the genus Allium, having long stalks bearing clusters of variously colored flowers and including many ornamental and food plants, such as onions, leeks, chives, garlic, and shallots.
