### ISSUE TITLE
bug: IPv4 Exit Policy Summary displayed incorrectly

### ISSUE THREAD

**Issue by nusenu** [tempname1024/allium#6]
Example:
https://yui.cat/relay/364B9207753AC054BDC646AF6AAC7168C967C5A0.html

says
> IPv4 Exit Policy Summary
> accept: 53

but the raw data is something else:
https://onionoo.torproject.org/details?lookup=0110851758EA4986268DE30DE1CA2516797C827F

```
"exit_policy_summary":{"accept":["53","80","443"]}
```

https://metrics.torproject.org/rs.html#details/364B9207753AC054BDC646AF6AAC7168C967C5A0

**Comment by tempname1024** [comment]
Ah, definitely an oversight on my part. Thanks for reporting.
